plugins:
  required:
    git: 3.9.1
    pipeline-model-definition: 1.3.2
    pipeline-stage-step: 2.3
    pipeline-maven: 3.5.12
    workflow-aggregator: 2.5
    junit: 1.25
    blueocean: latest
    job-dsl: latest
    jobConfigHistory: latest
    gradle: latest
    warnings-ng: latest
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
jenkins:
  systemMessage: "Welcome to Jenkins." 
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 3
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 2
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
tool:
  dockerTool:
    installations:
    - name: "docker"
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    installations:
    - home: "/docker-java-home"
      name: "jdk"
  maven:
    installations:
    - name: "maven"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.5.4"
  gradle:
    installations:
    - name: "Default"
      properties:
      - installSource:
          installers:
          - gradleInstaller:
              id: "5.4"
jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/rgaryburgess/lv-test.git' }
                        branch 'master'
                        extensions {}
                    }
                  }
              }
          }
      }

